### ISSUE TITLE
Hi, I would like to buy your firmware!

### ISSUE THREAD

**Issue by thesmallcreeper** [ariskyr/Billiards_Firmware#1]
Hi, I am Ali Papa from Dubai.
I want to buy this 100% bulletproof firmware for 10 barrels of slow petrol.
My dad would choose camel instead but I give you slow petrol.
Please answer me soon before Dubai gets under the sea.
Going now, septic tank just arrived.

**Comment by ariskyr** [comment]
Sorry but I only accept pure bred mongolian camels for this.
Preferably virgin.
